version: '3'

services:
  app:
    build:
      context: ./container/php
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DATABASE_USER: 'app'
      DATABASE_PASSWORD: 'INWAJ9jn0caTkdjmK118egYydjXZTBz4pmcdKJsrAwU='
      DATABASE_NAME: test
      DATABASE_PORT: 5432
      DATABASE_HOST: database
    depends_on:
      - database
    networks:
      - test-app
    working_dir: /var/www
    volumes:
      - .:/var/www:delegated
      - ./container/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./var/log/php/:/var/log/
  nginx:
    image: nginx:alpine
    depends_on:
      - app
    networks:
      - test-app
    ports:
      - 6589:80
    volumes:
      - .:/var/www
      - ./container/nginx/conf.d/:/etc/nginx/conf.d/
      - ./var/log/:/var/log
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: 'app'
      POSTGRES_PASSWORD: 'INWAJ9jn0caTkdjmK118egYydjXZTBz4pmcdKJsrAwU='
      POSTGRES_DB: test
    networks:
      - test-app
    ports:
      - 5432:5432
    volumes:
      - "fs-db:/var/lib/postgresql/data"
networks:
  test-app:
    driver: bridge

volumes:
  fs-db:
    driver: local
